name: Build Loop

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app/Contents/Developer

      - name: Set Swift Version
        run: |
          echo "Setting Swift version to 4.0"
          defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks 1

      - name: Install dependencies
        run: |
          brew install cocoapods
          pod install --repo-update

      - name: Build Loop
        run: |
          xcodebuild clean build \
            -workspace Loop.xcworkspace \
            -scheme Loop \
            -configuration Release \
            SWIFT_VERSION=4.0 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
